#%RAML 1.0
title: address-api
types:
  address: !include address-datatype.raml
  address_no_id: !include address-no-id-datatype.raml

/address:
  get:
    responses:
        200:
          body:
            application/json:
              type: address[]
              examples:
                output: !include examples/address-examples.raml
        404:
          body:
            application/json:
              example:
                message: Service not found
        500:
          body:
            application/json:
              example:
                message: Internal Server error
  post:
    body:
      application/json:
        type: address_no_id
        examples:
          input:  !include examples/address-no-id-example.raml
    responses:
      201:
        body:
          application/json:
            type: address
            examples:
              output : !include examples/address-example.raml
      404:
          body:
            application/json:
              example:
                message: Service not found
      500:
          body:
            application/json:
              example:
                message: Internal Server error

  patch:
    body:
      application/json:
        type: address
        examples:
          input:  !include examples/address-example.raml
    responses:
      201:
        body:
          application/json:
            type: address
            examples:
              output : !include examples/address-example.raml
      404:
          body:
            application/json:
              example:
                message: Service not found
      500:
          body:
            application/json:
              example:
                message: Internal Server error
  /{ID}:
    get:
      responses:
        200:
          body:
            application/json:
              type: address
              examples:
                output: !include examples/address-example.raml
        404:
          body:
            application/json:
              example:
                message: Service not found
        500:
          body:
            application/json:
              example:
                message: Internal Server error      
    delete:
      responses:
        201:
          body:
            application/json:
              example:
                message: address deleted successfully
        404:
          body:
            application/json:
              example:
                message: Service not found
        500:
          body:
            application/json:
              example:
                message: Internal Server error