USE [master]
GO
/****** Object:  Database [ContactsDB]    Script Date: 10/8/2019 1:06:29 PM ******/
CREATE DATABASE [ContactsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContactsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ContactsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContactsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ContactsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ContactsDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContactsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ContactsDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ContactsDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ContactsDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ContactsDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ContactsDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ContactsDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ContactsDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ContactsDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ContactsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ContactsDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ContactsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ContactsDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ContactsDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ContactsDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ContactsDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ContactsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ContactsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ContactsDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ContactsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ContactsDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ContactsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ContactsDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ContactsDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ContactsDB] SET  MULTI_USER 
GO
ALTER DATABASE [ContactsDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ContactsDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ContactsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ContactsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ContactsDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ContactsDB] SET QUERY_STORE = OFF
GO
USE [ContactsDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [ContactsDB]
GO
/****** Object:  Table [dbo].[ADDRESS]    Script Date: 10/8/2019 1:06:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADDRESS](
	[ADDRESS_ID] [int] IDENTITY(1,1) NOT NULL,
	[NUMBER] [int] NULL,
	[STREET] [varchar](100) NULL,
	[UNIT] [varchar](10) NULL,
	[CITY] [varchar](100) NULL,
	[STATE] [varchar](50) NULL,
	[ZIPCODE] [varchar](10) NULL,
	[LAST_MODIFIED_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTACT]    Script Date: 10/8/2019 1:06:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTACT](
	[CONTACT_ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [varchar](10) NOT NULL,
	[VALUE] [varchar](50) NOT NULL,
	[PREFERRED] [bit] NULL,
	[LAST_MODIFIED_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBER]    Script Date: 10/8/2019 1:06:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBER](
	[MEMBER_ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](200) NULL,
	[Last_Name] [varchar](200) NULL,
	[DOB] [date] NULL,
	[GENDER] [varchar](10) NULL,
	[TITLE] [varchar](50) NULL,
	[LAST_MODIFIED_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_MEMBER] PRIMARY KEY CLUSTERED 
(
	[MEMBER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBER_ADDRESS]    Script Date: 10/8/2019 1:06:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBER_ADDRESS](
	[MEMBER_ADDRESS_ID] [int] IDENTITY(1,1) NOT NULL,
	[MEMBER_ID] [int] NOT NULL,
	[ADDRESS_ID] [int] NOT NULL,
	[LAST_MODIFIED_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBER_CONTACT]    Script Date: 10/8/2019 1:06:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBER_CONTACT](
	[MEMBER_CONTACT_ID] [int] IDENTITY(1,1) NOT NULL,
	[MEMBER_ID] [int] NOT NULL,
	[CONTACT_ID] [int] NOT NULL,
	[LAST_MODIFIED_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADDRESS] ADD  CONSTRAINT [DF_ADDRESS_MODIFIED_DATE]  DEFAULT (getdate()) FOR [LAST_MODIFIED_DATE]
GO
ALTER TABLE [dbo].[ADDRESS] ADD  CONSTRAINT [DF_ADDRESS_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[CONTACT] ADD  CONSTRAINT [DF_CONTACT_PREFERRED]  DEFAULT ((0)) FOR [PREFERRED]
GO
ALTER TABLE [dbo].[CONTACT] ADD  CONSTRAINT [DF_CONTACT_MODIFIED_DATE]  DEFAULT (getdate()) FOR [LAST_MODIFIED_DATE]
GO
ALTER TABLE [dbo].[CONTACT] ADD  CONSTRAINT [DF_CONTACT_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[MEMBER] ADD  CONSTRAINT [DF_MEMBER_MODIFIED_DATE]  DEFAULT (getdate()) FOR [LAST_MODIFIED_DATE]
GO
ALTER TABLE [dbo].[MEMBER] ADD  CONSTRAINT [DF_MEMBER_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[MEMBER_ADDRESS] ADD  CONSTRAINT [DF_MEMBER_ADDRESS_MODIFIED_DATE]  DEFAULT (getdate()) FOR [LAST_MODIFIED_DATE]
GO
ALTER TABLE [dbo].[MEMBER_ADDRESS] ADD  CONSTRAINT [DF_MEMBER_ADDRESS_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[MEMBER_CONTACT] ADD  CONSTRAINT [DF_MEMBER_CONTACT_MODIFIED_DATE]  DEFAULT (getdate()) FOR [LAST_MODIFIED_DATE]
GO
ALTER TABLE [dbo].[MEMBER_CONTACT] ADD  CONSTRAINT [DF_MEMBER_CONTACT_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
USE [master]
GO
ALTER DATABASE [ContactsDB] SET  READ_WRITE 
GO
