#%RAML 1.0 NamedExample
value:
  -
    id: 1
    type: "email"
    value : "rkvajrala@gmail.com"
    preferred: true
  -
    id: 1
    type: "email"
    value : "rkvajrala@gmail.com"
    preferred: true
